// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/notifications_integration.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationsIntegration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata about this resource
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Write only reporter specific data
	ReporterData  *ReporterData `protobuf:"bytes,245278792,opt,name=reporter_data,proto3" json:"reporter_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationsIntegration) Reset() {
	*x = NotificationsIntegration{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsIntegration) ProtoMessage() {}

func (x *NotificationsIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationsIntegration.ProtoReflect.Descriptor instead.
func (*NotificationsIntegration) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationsIntegration) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NotificationsIntegration) GetReporterData() *ReporterData {
	if x != nil {
		return x.ReporterData
	}
	return nil
}

var File_kessel_inventory_v1beta1_resources_notifications_integration_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDesc = "" +
	"\n" +
	"Bkessel/inventory/v1beta1/resources/notifications_integration.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bbuf/validate/validate.proto\x1a1kessel/inventory/v1beta1/resources/metadata.proto\x1a6kessel/inventory/v1beta1/resources/reporter_data.proto\"\xca\x01\n" +
	"\x18NotificationsIntegration\x12H\n" +
	"\bmetadata\x18\x01 \x01(\v2,.kessel.inventory.v1beta1.resources.MetadataR\bmetadata\x12d\n" +
	"\rreporter_data\x18\xc8\xd0\xfat \x01(\v20.kessel.inventory.v1beta1.resources.ReporterDataB\t\xe0A\x04\xbaH\x03\xc8\x01\x01R\rreporter_dataB\xc3\x02\n" +
	"&com.kessel.inventory.v1beta1.resourcesB\x1dNotificationsIntegrationProtoP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resources\xa2\x02\x04KIVR\xaa\x02\"Kessel.Inventory.V1beta1.Resources\xca\x02\"Kessel\\Inventory\\V1beta1\\Resources\xe2\x02.Kessel\\Inventory\\V1beta1\\Resources\\GPBMetadata\xea\x02%Kessel::Inventory::V1beta1::Resourcesb\x06proto3"

var (
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_notifications_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta1_resources_notifications_integration_proto_goTypes = []any{
	(*NotificationsIntegration)(nil), // 0: kessel.inventory.v1beta1.resources.NotificationsIntegration
	(*Metadata)(nil),                 // 1: kessel.inventory.v1beta1.resources.Metadata
	(*ReporterData)(nil),             // 2: kessel.inventory.v1beta1.resources.ReporterData
}
var file_kessel_inventory_v1beta1_resources_notifications_integration_proto_depIdxs = []int32{
	1, // 0: kessel.inventory.v1beta1.resources.NotificationsIntegration.metadata:type_name -> kessel.inventory.v1beta1.resources.Metadata
	2, // 1: kessel.inventory.v1beta1.resources.NotificationsIntegration.reporter_data:type_name -> kessel.inventory.v1beta1.resources.ReporterData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_notifications_integration_proto_init() }
func file_kessel_inventory_v1beta1_resources_notifications_integration_proto_init() {
	if File_kessel_inventory_v1beta1_resources_notifications_integration_proto != nil {
		return
	}
	file_kessel_inventory_v1beta1_resources_metadata_proto_init()
	file_kessel_inventory_v1beta1_resources_reporter_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_notifications_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_notifications_integration_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_notifications_integration_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_notifications_integration_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_notifications_integration_proto = out.File
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_depIdxs = nil
}
