version: "2" 
linters:
  enable:
    # Start: Defaults
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    # End: Defaults
formatters:
  enable:
    - goimports
issues:
  skip-dirs:
    - ./_proto
  # Maximum count of issues with the same text (0 = no limit)
  max-same-issues: 0
