// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/notifications_integrations_service.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	authz "github.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/authz"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNotificationsIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The NotificationsIntegration to create in Kessel Asset Inventory
	Integration   *NotificationsIntegration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationsIntegrationRequest) Reset() {
	*x = CreateNotificationsIntegrationRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsIntegrationRequest) ProtoMessage() {}

func (x *CreateNotificationsIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationsIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNotificationsIntegrationRequest) GetIntegration() *NotificationsIntegration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type CreateNotificationsIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationsIntegrationResponse) Reset() {
	*x = CreateNotificationsIntegrationResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsIntegrationResponse) ProtoMessage() {}

func (x *CreateNotificationsIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsIntegrationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationsIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{1}
}

type UpdateNotificationsIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be updated will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	Integration   *NotificationsIntegration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationsIntegrationRequest) Reset() {
	*x = UpdateNotificationsIntegrationRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationsIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationsIntegrationRequest) ProtoMessage() {}

func (x *UpdateNotificationsIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationsIntegrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationsIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNotificationsIntegrationRequest) GetIntegration() *NotificationsIntegration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type UpdateNotificationsIntegrationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be updated will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	Integration   *NotificationsIntegration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationsIntegrationsRequest) Reset() {
	*x = UpdateNotificationsIntegrationsRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationsIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationsIntegrationsRequest) ProtoMessage() {}

func (x *UpdateNotificationsIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationsIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationsIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNotificationsIntegrationsRequest) GetIntegration() *NotificationsIntegration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type UpdateNotificationsIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationsIntegrationResponse) Reset() {
	*x = UpdateNotificationsIntegrationResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationsIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationsIntegrationResponse) ProtoMessage() {}

func (x *UpdateNotificationsIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationsIntegrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationsIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{4}
}

type UpdateNotificationsIntegrationsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpsertsCompleted int32                  `protobuf:"varint,1,opt,name=upserts_completed,json=upsertsCompleted,proto3" json:"upserts_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateNotificationsIntegrationsResponse) Reset() {
	*x = UpdateNotificationsIntegrationsResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationsIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationsIntegrationsResponse) ProtoMessage() {}

func (x *UpdateNotificationsIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationsIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationsIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNotificationsIntegrationsResponse) GetUpsertsCompleted() int32 {
	if x != nil {
		return x.UpsertsCompleted
	}
	return 0
}

type DeleteNotificationsIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be deleted will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	ReporterData  *ReporterData `protobuf:"bytes,1,opt,name=reporter_data,proto3" json:"reporter_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationsIntegrationRequest) Reset() {
	*x = DeleteNotificationsIntegrationRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationsIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationsIntegrationRequest) ProtoMessage() {}

func (x *DeleteNotificationsIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationsIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationsIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotificationsIntegrationRequest) GetReporterData() *ReporterData {
	if x != nil {
		return x.ReporterData
	}
	return nil
}

type DeleteNotificationsIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationsIntegrationResponse) Reset() {
	*x = DeleteNotificationsIntegrationResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationsIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationsIntegrationResponse) ProtoMessage() {}

func (x *DeleteNotificationsIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationsIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationsIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{7}
}

type ListNotificationsIntegrationsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ResourceType  *authz.ObjectType       `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Relation      string                  `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *authz.SubjectReference `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Parent        *authz.ObjectReference  `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsIntegrationsRequest) Reset() {
	*x = ListNotificationsIntegrationsRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsIntegrationsRequest) ProtoMessage() {}

func (x *ListNotificationsIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListNotificationsIntegrationsRequest) GetResourceType() *authz.ObjectType {
	if x != nil {
		return x.ResourceType
	}
	return nil
}

func (x *ListNotificationsIntegrationsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListNotificationsIntegrationsRequest) GetSubject() *authz.SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ListNotificationsIntegrationsRequest) GetParent() *authz.ObjectReference {
	if x != nil {
		return x.Parent
	}
	return nil
}

type ListNotificationsIntegrationsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Integrations  *NotificationsIntegration `protobuf:"bytes,1,opt,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsIntegrationsResponse) Reset() {
	*x = ListNotificationsIntegrationsResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsIntegrationsResponse) ProtoMessage() {}

func (x *ListNotificationsIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListNotificationsIntegrationsResponse) GetIntegrations() *NotificationsIntegration {
	if x != nil {
		return x.Integrations
	}
	return nil
}

var File_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDesc = "" +
	"\n" +
	"Kkessel/inventory/v1beta1/resources/notifications_integrations_service.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a+kessel/inventory/v1beta1/authz/common.proto\x1aBkessel/inventory/v1beta1/resources/notifications_integration.proto\x1a6kessel/inventory/v1beta1/resources/reporter_data.proto\"\x8f\x01\n" +
	"%CreateNotificationsIntegrationRequest\x12f\n" +
	"\vintegration\x18\x01 \x01(\v2<.kessel.inventory.v1beta1.resources.NotificationsIntegrationB\x06\xbaH\x03\xc8\x01\x01R\vintegration\"(\n" +
	"&CreateNotificationsIntegrationResponse\"\x8f\x01\n" +
	"%UpdateNotificationsIntegrationRequest\x12f\n" +
	"\vintegration\x18\x01 \x01(\v2<.kessel.inventory.v1beta1.resources.NotificationsIntegrationB\x06\xbaH\x03\xc8\x01\x01R\vintegration\"\x90\x01\n" +
	"&UpdateNotificationsIntegrationsRequest\x12f\n" +
	"\vintegration\x18\x01 \x01(\v2<.kessel.inventory.v1beta1.resources.NotificationsIntegrationB\x06\xbaH\x03\xc8\x01\x01R\vintegration\"(\n" +
	"&UpdateNotificationsIntegrationResponse\"V\n" +
	"'UpdateNotificationsIntegrationsResponse\x12+\n" +
	"\x11upserts_completed\x18\x01 \x01(\x05R\x10upsertsCompleted\"\x87\x01\n" +
	"%DeleteNotificationsIntegrationRequest\x12^\n" +
	"\rreporter_data\x18\x01 \x01(\v20.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\"(\n" +
	"&DeleteNotificationsIntegrationResponse\"\xc9\x02\n" +
	"$ListNotificationsIntegrationsRequest\x12W\n" +
	"\rresource_type\x18\x01 \x01(\v2*.kessel.inventory.v1beta1.authz.ObjectTypeB\x06\xbaH\x03\xc8\x01\x01R\fresourceType\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12R\n" +
	"\asubject\x18\x03 \x01(\v20.kessel.inventory.v1beta1.authz.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\x12O\n" +
	"\x06parent\x18\x04 \x01(\v2/.kessel.inventory.v1beta1.authz.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x06parent\"\x89\x01\n" +
	"%ListNotificationsIntegrationsResponse\x12`\n" +
	"\fintegrations\x18\x01 \x01(\v2<.kessel.inventory.v1beta1.resources.NotificationsIntegrationR\fintegrations2\xec\t\n" +
	"%KesselNotificationsIntegrationService\x12\xff\x01\n" +
	"\x1eCreateNotificationsIntegration\x12I.kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationRequest\x1aJ.kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationResponse\"F\x82\xd3\xe4\x93\x02@:\x01*\";/api/inventory/v1beta1/resources/notifications-integrations\x12\xff\x01\n" +
	"\x1eUpdateNotificationsIntegration\x12I.kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationRequest\x1aJ.kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationResponse\"F\x82\xd3\xe4\x93\x02@:\x01*\x1a;/api/inventory/v1beta1/resources/notifications-integrations\x12\xbe\x01\n" +
	"\x1fUpdateNotificationsIntegrations\x12J.kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsRequest\x1aK.kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsResponse\"\x00(\x01\x12\xff\x01\n" +
	"\x1eDeleteNotificationsIntegration\x12I.kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationRequest\x1aJ.kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationResponse\"F\x82\xd3\xe4\x93\x02@:\x01**;/api/inventory/v1beta1/resources/notifications-integrations\x12\xfb\x01\n" +
	"\x1dListNotificationsIntegrations\x12H.kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest\x1aI.kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsResponse\"C\x82\xd3\xe4\x93\x02=\x12;/api/inventory/v1beta1/resources/notifications-integrations0\x01B\x86\x01\n" +
	"2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

var (
	file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_goTypes = []any{
	(*CreateNotificationsIntegrationRequest)(nil),   // 0: kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationRequest
	(*CreateNotificationsIntegrationResponse)(nil),  // 1: kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationResponse
	(*UpdateNotificationsIntegrationRequest)(nil),   // 2: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationRequest
	(*UpdateNotificationsIntegrationsRequest)(nil),  // 3: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsRequest
	(*UpdateNotificationsIntegrationResponse)(nil),  // 4: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationResponse
	(*UpdateNotificationsIntegrationsResponse)(nil), // 5: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsResponse
	(*DeleteNotificationsIntegrationRequest)(nil),   // 6: kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationRequest
	(*DeleteNotificationsIntegrationResponse)(nil),  // 7: kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationResponse
	(*ListNotificationsIntegrationsRequest)(nil),    // 8: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest
	(*ListNotificationsIntegrationsResponse)(nil),   // 9: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsResponse
	(*NotificationsIntegration)(nil),                // 10: kessel.inventory.v1beta1.resources.NotificationsIntegration
	(*ReporterData)(nil),                            // 11: kessel.inventory.v1beta1.resources.ReporterData
	(*authz.ObjectType)(nil),                        // 12: kessel.inventory.v1beta1.authz.ObjectType
	(*authz.SubjectReference)(nil),                  // 13: kessel.inventory.v1beta1.authz.SubjectReference
	(*authz.ObjectReference)(nil),                   // 14: kessel.inventory.v1beta1.authz.ObjectReference
}
var file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_depIdxs = []int32{
	10, // 0: kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationRequest.integration:type_name -> kessel.inventory.v1beta1.resources.NotificationsIntegration
	10, // 1: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationRequest.integration:type_name -> kessel.inventory.v1beta1.resources.NotificationsIntegration
	10, // 2: kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsRequest.integration:type_name -> kessel.inventory.v1beta1.resources.NotificationsIntegration
	11, // 3: kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationRequest.reporter_data:type_name -> kessel.inventory.v1beta1.resources.ReporterData
	12, // 4: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest.resource_type:type_name -> kessel.inventory.v1beta1.authz.ObjectType
	13, // 5: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest.subject:type_name -> kessel.inventory.v1beta1.authz.SubjectReference
	14, // 6: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest.parent:type_name -> kessel.inventory.v1beta1.authz.ObjectReference
	10, // 7: kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsResponse.integrations:type_name -> kessel.inventory.v1beta1.resources.NotificationsIntegration
	0,  // 8: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.CreateNotificationsIntegration:input_type -> kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationRequest
	2,  // 9: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.UpdateNotificationsIntegration:input_type -> kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationRequest
	3,  // 10: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.UpdateNotificationsIntegrations:input_type -> kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsRequest
	6,  // 11: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.DeleteNotificationsIntegration:input_type -> kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationRequest
	8,  // 12: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.ListNotificationsIntegrations:input_type -> kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsRequest
	1,  // 13: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.CreateNotificationsIntegration:output_type -> kessel.inventory.v1beta1.resources.CreateNotificationsIntegrationResponse
	4,  // 14: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.UpdateNotificationsIntegration:output_type -> kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationResponse
	5,  // 15: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.UpdateNotificationsIntegrations:output_type -> kessel.inventory.v1beta1.resources.UpdateNotificationsIntegrationsResponse
	7,  // 16: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.DeleteNotificationsIntegration:output_type -> kessel.inventory.v1beta1.resources.DeleteNotificationsIntegrationResponse
	9,  // 17: kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService.ListNotificationsIntegrations:output_type -> kessel.inventory.v1beta1.resources.ListNotificationsIntegrationsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_init() }
func file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_init() {
	if File_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto != nil {
		return
	}
	file_kessel_inventory_v1beta1_resources_notifications_integration_proto_init()
	file_kessel_inventory_v1beta1_resources_reporter_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto = out.File
	file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_notifications_integrations_service_proto_depIdxs = nil
}
