// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/rhel_hosts_service.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRhelHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Rhel Host to create in Kessel Asset Inventory
	RhelHost      *RhelHost `protobuf:"bytes,1,opt,name=rhel_host,proto3" json:"rhel_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRhelHostRequest) Reset() {
	*x = CreateRhelHostRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRhelHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRhelHostRequest) ProtoMessage() {}

func (x *CreateRhelHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRhelHostRequest.ProtoReflect.Descriptor instead.
func (*CreateRhelHostRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRhelHostRequest) GetRhelHost() *RhelHost {
	if x != nil {
		return x.RhelHost
	}
	return nil
}

type CreateRhelHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRhelHostResponse) Reset() {
	*x = CreateRhelHostResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRhelHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRhelHostResponse) ProtoMessage() {}

func (x *CreateRhelHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRhelHostResponse.ProtoReflect.Descriptor instead.
func (*CreateRhelHostResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{1}
}

type UpdateRhelHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be updated will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	RhelHost      *RhelHost `protobuf:"bytes,1,opt,name=rhel_host,proto3" json:"rhel_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRhelHostRequest) Reset() {
	*x = UpdateRhelHostRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRhelHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRhelHostRequest) ProtoMessage() {}

func (x *UpdateRhelHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRhelHostRequest.ProtoReflect.Descriptor instead.
func (*UpdateRhelHostRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRhelHostRequest) GetRhelHost() *RhelHost {
	if x != nil {
		return x.RhelHost
	}
	return nil
}

type UpdateRhelHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRhelHostResponse) Reset() {
	*x = UpdateRhelHostResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRhelHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRhelHostResponse) ProtoMessage() {}

func (x *UpdateRhelHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRhelHostResponse.ProtoReflect.Descriptor instead.
func (*UpdateRhelHostResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{3}
}

type DeleteRhelHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be updated will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	ReporterData  *ReporterData `protobuf:"bytes,1,opt,name=reporter_data,proto3" json:"reporter_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRhelHostRequest) Reset() {
	*x = DeleteRhelHostRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRhelHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRhelHostRequest) ProtoMessage() {}

func (x *DeleteRhelHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRhelHostRequest.ProtoReflect.Descriptor instead.
func (*DeleteRhelHostRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRhelHostRequest) GetReporterData() *ReporterData {
	if x != nil {
		return x.ReporterData
	}
	return nil
}

type DeleteRhelHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRhelHostResponse) Reset() {
	*x = DeleteRhelHostResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRhelHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRhelHostResponse) ProtoMessage() {}

func (x *DeleteRhelHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRhelHostResponse.ProtoReflect.Descriptor instead.
func (*DeleteRhelHostResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP(), []int{5}
}

var File_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDesc = "" +
	"\n" +
	";kessel/inventory/v1beta1/resources/rhel_hosts_service.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a2kessel/inventory/v1beta1/resources/rhel_host.proto\x1a6kessel/inventory/v1beta1/resources/reporter_data.proto\"k\n" +
	"\x15CreateRhelHostRequest\x12R\n" +
	"\trhel_host\x18\x01 \x01(\v2,.kessel.inventory.v1beta1.resources.RhelHostB\x06\xbaH\x03\xc8\x01\x01R\trhel_host\"\x18\n" +
	"\x16CreateRhelHostResponse\"k\n" +
	"\x15UpdateRhelHostRequest\x12R\n" +
	"\trhel_host\x18\x01 \x01(\v2,.kessel.inventory.v1beta1.resources.RhelHostB\x06\xbaH\x03\xc8\x01\x01R\trhel_host\"\x18\n" +
	"\x16UpdateRhelHostResponse\"w\n" +
	"\x15DeleteRhelHostRequest\x12^\n" +
	"\rreporter_data\x18\x01 \x01(\v20.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\"\x18\n" +
	"\x16DeleteRhelHostResponse2\xdd\x04\n" +
	"\x15KesselRhelHostService\x12\xbf\x01\n" +
	"\x0eCreateRhelHost\x129.kessel.inventory.v1beta1.resources.CreateRhelHostRequest\x1a:.kessel.inventory.v1beta1.resources.CreateRhelHostResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/inventory/v1beta1/resources/rhel-hosts\x12\xbf\x01\n" +
	"\x0eUpdateRhelHost\x129.kessel.inventory.v1beta1.resources.UpdateRhelHostRequest\x1a:.kessel.inventory.v1beta1.resources.UpdateRhelHostResponse\"6\x82\xd3\xe4\x93\x020:\x01*\x1a+/api/inventory/v1beta1/resources/rhel-hosts\x12\xbf\x01\n" +
	"\x0eDeleteRhelHost\x129.kessel.inventory.v1beta1.resources.DeleteRhelHostRequest\x1a:.kessel.inventory.v1beta1.resources.DeleteRhelHostResponse\"6\x82\xd3\xe4\x93\x020:\x01**+/api/inventory/v1beta1/resources/rhel-hostsB\x86\x01\n" +
	"2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

var (
	file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_goTypes = []any{
	(*CreateRhelHostRequest)(nil),  // 0: kessel.inventory.v1beta1.resources.CreateRhelHostRequest
	(*CreateRhelHostResponse)(nil), // 1: kessel.inventory.v1beta1.resources.CreateRhelHostResponse
	(*UpdateRhelHostRequest)(nil),  // 2: kessel.inventory.v1beta1.resources.UpdateRhelHostRequest
	(*UpdateRhelHostResponse)(nil), // 3: kessel.inventory.v1beta1.resources.UpdateRhelHostResponse
	(*DeleteRhelHostRequest)(nil),  // 4: kessel.inventory.v1beta1.resources.DeleteRhelHostRequest
	(*DeleteRhelHostResponse)(nil), // 5: kessel.inventory.v1beta1.resources.DeleteRhelHostResponse
	(*RhelHost)(nil),               // 6: kessel.inventory.v1beta1.resources.RhelHost
	(*ReporterData)(nil),           // 7: kessel.inventory.v1beta1.resources.ReporterData
}
var file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_depIdxs = []int32{
	6, // 0: kessel.inventory.v1beta1.resources.CreateRhelHostRequest.rhel_host:type_name -> kessel.inventory.v1beta1.resources.RhelHost
	6, // 1: kessel.inventory.v1beta1.resources.UpdateRhelHostRequest.rhel_host:type_name -> kessel.inventory.v1beta1.resources.RhelHost
	7, // 2: kessel.inventory.v1beta1.resources.DeleteRhelHostRequest.reporter_data:type_name -> kessel.inventory.v1beta1.resources.ReporterData
	0, // 3: kessel.inventory.v1beta1.resources.KesselRhelHostService.CreateRhelHost:input_type -> kessel.inventory.v1beta1.resources.CreateRhelHostRequest
	2, // 4: kessel.inventory.v1beta1.resources.KesselRhelHostService.UpdateRhelHost:input_type -> kessel.inventory.v1beta1.resources.UpdateRhelHostRequest
	4, // 5: kessel.inventory.v1beta1.resources.KesselRhelHostService.DeleteRhelHost:input_type -> kessel.inventory.v1beta1.resources.DeleteRhelHostRequest
	1, // 6: kessel.inventory.v1beta1.resources.KesselRhelHostService.CreateRhelHost:output_type -> kessel.inventory.v1beta1.resources.CreateRhelHostResponse
	3, // 7: kessel.inventory.v1beta1.resources.KesselRhelHostService.UpdateRhelHost:output_type -> kessel.inventory.v1beta1.resources.UpdateRhelHostResponse
	5, // 8: kessel.inventory.v1beta1.resources.KesselRhelHostService.DeleteRhelHost:output_type -> kessel.inventory.v1beta1.resources.DeleteRhelHostResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_init() }
func file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_init() {
	if File_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto != nil {
		return
	}
	file_kessel_inventory_v1beta1_resources_rhel_host_proto_init()
	file_kessel_inventory_v1beta1_resources_reporter_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto = out.File
	file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_rhel_hosts_service_proto_depIdxs = nil
}
